server:
  port: 8082
logging:
  level:
    org:
      springframework:
        security=DEBUG:
spring:
  security:
    oauth2:
      keycloak:
        jwt:
          issuer-uri: http://localhost:8080/realms/system
      client:
        registration:
          keycloak:
            client-id: service-client
            client-secret: Sm8TiKr6XSL2yaEaxRITjwbyLs8yl4lf
            client-authentication-method: client_secret_jwt
            authorization-grant-type: client_credentials
            scope: openid, profile, email
            issuer-uri: http://localhost:8080/realms/external
            issuer-realm: http://localhost:8080/realms/system
            token-uri: http://localhost:8080/realms/system/protocol/openid-connect/token
            jwk-set-uri: http://localhost:8080/realms/system/protocol/openid-connect/certs
            user-info-uri: http://localhost:8080/realms/system/protocol/openid-connect/userinfo
            authorization-uri: http://localhost:8080/realms/system/protocol/openid-connect/auth
            redirect-uri: http://localhost:8082/login/oauth2/code/callback
            provider: keycloak
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/system
            authorization-uri: http://localhost:8080/realms/system/protocol/openid-connect/auth
            token-uri: http://localhost:8080/realms/system/protocol/openid-connect/token

